#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Irrigation system"

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudTemperatureSensor temp_1;
  int humid_1;
  int moist_1;
  int servo_1;
  bool m_1;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <DHT.h>
#include <Servo.h>

float h,t;
int m;
const int motor_r=35;
const int temp_pin=4;
const int m_pin=32;
const int ser_pin=34;
Servo myservo;
DHT dht(temp_pin,DHT11);


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  dht.begin();
  myservo.attach(ser_pin);
  pinMode(motor_r,OUTPUT);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you'll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here

  h = dht.readHumidity();
  humid_1=h;

  // Read temperature as Celsius (the default)
  t = dht.readTemperature();
  temp_1=t;
  m=analogRead(m_pin);
  moist_1=map(m,0,1024,0,100);


}




/*
  Since M1 is READ_WRITE variable, onM1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onM1Change()  {
  if(m_1==1)
  {
    digitalWrite(motor_r,HIGH);

  }
  else
  {
    digitalWrite(motor_r,LOW);
  }
  // Add your code here to act upon M1 change
}

/*
  Since Servo1 is READ_WRITE variable, onServo1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onServo1Change()  {
  int angle;
  angle=map(servo_1,0,50,0,180);
  myservo.write(angle);

  // Add your code here to act upon Servo1 change
}
