// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "YOUR_DEVICE_LOGIN_NAME";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onServo1Change();
void onM1Change();

CloudTemperatureSensor temp_1;
int humid_1;
int moist_1;
int servo_1;
bool m_1;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(temp_1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humid_1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(moist_1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(servo_1, READWRITE, ON_CHANGE, onServo1Change);
  ArduinoCloud.addProperty(m_1, READWRITE, ON_CHANGE, onM1Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
